apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: node-pipeline
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: js-test
      taskRef:
        name: js-test
      resources:
        inputs:
          - name: source
            resource: git-source
    - name: build-tag-push
      taskRef:
        name: build-tag-push
      runAfter: [js-test]
      resources:
        inputs:
          - name: source
            resource: git-source
        outputs:
          - name: image
            resource: docker-image
    - name: deploy
      taskRef:
        name: deploy
      runAfter: [build-push]
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
    - name: health-check
      taskRef:
        name: health-check
      runAfter: [deploy]
      resources:
        inputs:
          - name: source
            resource: git-source
    - name: helm-package
      taskRef:
        name: helm-package
      runAfter: [health-check]
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
    - name: gitops
      taskRef:
        name: gitops
      runAfter: [helm-package]
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
